[package]
name = "alef-compiler"
version = "0.0.1-alpha"
description = "The AOT Compiler of Alef Component."
repository = "https://github.com/alephjs/alef-component"
license = "MIT"
authors = ["The Alef Component authors"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
anyhow = "1.0.37" 
indexmap = "1.6.1"
lazy_static = "1.4.0" 
regex = "1.4.2" 
serde = { version = "1.0.118", features = ["derive"] }

# swc
# docs: https://swc.rs
swc_common = { version = "0.10.8", features = ["sourcemap"] }
swc_ecmascript = { version = "0.16.1", features = ["codegen", "parser",  "transforms", "visit"] }
swc_ecma_ast = "0.36.2"
swc_ecma_visit = "0.22.0"
swc_ecma_utils = "0.26.0"

# wasm-bindgen
# docs: https://rustwasm.github.io/docs/wasm-bindgen
wasm-bindgen = {version = "0.2.69", features = ["serde-serialize"]}
console_error_panic_hook = { version = "0.1.6", optional = true }

[profile.release]
# Tell `rustc` to optimize for speed
lto = true
