[package]
name = "alef"
version = "0.0.1-alpha"
description = "The AOT Compiler of Alef Component."
repository = "https://github.com/alephjs/alef-component"
license = "MIT"
authors = ["The Aleph.js authors"]
edition = "2018"

[lib]
name = "alef"

[dependencies]
anyhow = "1.0.37" 
indexmap = "1.6.1"
lazy_static = "1.4.0" 
regex = "1.4.2" 
serde = { version = "1.0.118", features = ["derive"] }

# swc
# docs: https://swc.rs
swc_common = { version = "0.10.8", features = ["sourcemap"] }
swc_ecmascript = { version = "0.16.1", features = ["codegen", "parser",  "transforms", "visit"] }
swc_ecma_ast = "0.36.2"
swc_ecma_visit = "0.22.0"
swc_ecma_utils = "0.26.0"
